// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SheridanNGO.Migrations
{
    [DbContext(typeof(DonationDbContext))]
    partial class DonationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SheridanNGO.Models.Campaign", b =>
                {
                    b.Property<int>("CampaignID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CauseCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GoalAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("NGOID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CampaignID");

                    b.HasIndex("NGOID");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("SheridanNGO.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("SheridanNGO.Models.Donation", b =>
                {
                    b.Property<int>("DonationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DonorID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NGOID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Recurring")
                        .HasColumnType("INTEGER");

                    b.HasKey("DonationID");

                    b.HasIndex("DonorID");

                    b.HasIndex("NGOID");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("SheridanNGO.Models.NGO", b =>
                {
                    b.Property<int>("NGOID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mission")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NGOID");

                    b.ToTable("NGOs");
                });

            modelBuilder.Entity("SheridanNGO.Models.Receipt", b =>
                {
                    b.Property<int>("ReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountDonated")
                        .HasColumnType("TEXT");

                    b.Property<int>("DonationID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ReceiptID");

                    b.HasIndex("DonationID");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("SheridanNGO.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SheridanNGO.Models.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Days")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("SheridanNGO.Models.Campaign", b =>
                {
                    b.HasOne("SheridanNGO.Models.NGO", "NGO")
                        .WithMany("Campaigns")
                        .HasForeignKey("NGOID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NGO");
                });

            modelBuilder.Entity("SheridanNGO.Models.Donation", b =>
                {
                    b.HasOne("SheridanNGO.Models.User", "Donor")
                        .WithMany("Donations")
                        .HasForeignKey("DonorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SheridanNGO.Models.NGO", "NGO")
                        .WithMany("Donations")
                        .HasForeignKey("NGOID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donor");

                    b.Navigation("NGO");
                });

            modelBuilder.Entity("SheridanNGO.Models.Receipt", b =>
                {
                    b.HasOne("SheridanNGO.Models.Donation", "Donation")
                        .WithMany()
                        .HasForeignKey("DonationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");
                });

            modelBuilder.Entity("SheridanNGO.Models.NGO", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("Donations");
                });

            modelBuilder.Entity("SheridanNGO.Models.User", b =>
                {
                    b.Navigation("Donations");
                });
#pragma warning restore 612, 618
        }
    }
}
